# TODO: Wenn wir das zu laufen kriegen, können wir ne ganze Serie im Blog machen. Daran beißt sich aktuell die ganze Java-Welt die Zähne aus ;-)
FROM oracle/graalvm-ce:20.0.0-java11 as graalvm
COPY . /home/app/parkhaus-manager
WORKDIR /home/app/parkhaus-manager
RUN gu install native-image
RUN native-image --no-server -cp target/parkhaus-manager-quarkus-1.0-SNAPSHOT.jar

FROM frolvlad/alpine-glibc
EXPOSE 8180
COPY --from=graalvm /home/app/parkhaus-manager .
ENTRYPOINT ["./parkhaus-manager"]
