FROM oracle/graalvm-ce:19.3.1 as graalvm
COPY . /home/app/parkhaus-manager
WORKDIR /home/app/parkhaus-manager
RUN gu install native-image
RUN native-image --no-server -cp target/parkhaus-manager-quarkus-1.0-SNAPSHOT.jar

FROM frolvlad/alpine-glibc
EXPOSE 8180
COPY --from=graalvm /home/app/parkhaus-manager .
ENTRYPOINT ["./parkhaus-manager"]
