FROM oracle/graalvm-ce:20.0.0-java11 as graalvm
COPY . /home/app/parkhaus-manager
WORKDIR /home/app/parkhaus-manager
RUN gu install native-image
RUN native-image --no-server -cp target/parkhaus-manager-micronaut-1.0-SNAPSHOT.jar

FROM frolvlad/alpine-glibc
EXPOSE 8280
COPY --from=graalvm /home/app/parkhaus-manager .
ENTRYPOINT ["./parkhaus-manager"]
